/*
 * SteganoView.java
 */

package stegano;

import org.jdesktop.application.Action;
import org.jdesktop.application.ResourceMap;
import org.jdesktop.application.SingleFrameApplication;
import org.jdesktop.application.FrameView;
import org.jdesktop.application.TaskMonitor;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;
import javax.swing.Icon;
import javax.swing.JDialog;
import javax.swing.JFrame;

/**
 * The application's main frame.
 */
public class SteganoView extends FrameView {

    public SteganoView(SingleFrameApplication app) {
        super(app);

        initComponents();

        initForm();

        // status bar initialization - message timeout, idle icon and busy animation, etc
        ResourceMap resourceMap = getResourceMap();
        int messageTimeout = resourceMap.getInteger("StatusBar.messageTimeout");
        messageTimer = new Timer(messageTimeout, new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                statusMessageLabel.setText("");
            }
        });
        messageTimer.setRepeats(false);
        int busyAnimationRate = resourceMap.getInteger("StatusBar.busyAnimationRate");
        for (int i = 0; i < busyIcons.length; i++) {
            busyIcons[i] = resourceMap.getIcon("StatusBar.busyIcons[" + i + "]");
        }
        busyIconTimer = new Timer(busyAnimationRate, new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                busyIconIndex = (busyIconIndex + 1) % busyIcons.length;
                statusAnimationLabel.setIcon(busyIcons[busyIconIndex]);
            }
        });
        idleIcon = resourceMap.getIcon("StatusBar.idleIcon");
        statusAnimationLabel.setIcon(idleIcon);
        progressBar.setVisible(false);

        // connecting action tasks to status bar via TaskMonitor
        TaskMonitor taskMonitor = new TaskMonitor(getApplication().getContext());
        taskMonitor.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                String propertyName = evt.getPropertyName();
                if ("started".equals(propertyName)) {
                    if (!busyIconTimer.isRunning()) {
                        statusAnimationLabel.setIcon(busyIcons[0]);
                        busyIconIndex = 0;
                        busyIconTimer.start();
                    }
                    progressBar.setVisible(true);
                    progressBar.setIndeterminate(true);
                } else if ("done".equals(propertyName)) {
                    busyIconTimer.stop();
                    statusAnimationLabel.setIcon(idleIcon);
                    progressBar.setVisible(false);
                    progressBar.setValue(0);
                } else if ("message".equals(propertyName)) {
                    String text = (String)(evt.getNewValue());
                    statusMessageLabel.setText((text == null) ? "" : text);
                    messageTimer.restart();
                } else if ("progress".equals(propertyName)) {
                    int value = (Integer)(evt.getNewValue());
                    progressBar.setVisible(true);
                    progressBar.setIndeterminate(false);
                    progressBar.setValue(value);
                }
            }
        });
    }

    @Action
    public void showAboutBox() {
        if (aboutBox == null) {
            JFrame mainFrame = SteganoApp.getApplication().getMainFrame();
            aboutBox = new SteganoAboutBox(mainFrame);
            aboutBox.setLocationRelativeTo(mainFrame);
        }
        SteganoApp.getApplication().show(aboutBox);
    }

    private void initForm() {
        // encrypt panel
        file1.setText(null);
        plaintext.setText(null);
        file2.setText(null);
        key.setText(null);

        vigenere.setSelected(false);
        opt1.setSelected(true);
        opt2.setSelected(false);

        imgBefore.removeAll();
        imgAfter.removeAll();

        valPSNR.setText("PSNR : ");

        //decrypt panel
        fileD.setText(null);
        keyD.setText(null);

        imgBeforeD.removeAll();
        imgAfterD.removeAll();

        valPSNRD.setText("PSNR : ");

        plaintextD.setText("Plaintext : ");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        tabbedPane = new javax.swing.JTabbedPane();
        encryptPanel = new javax.swing.JPanel();
        labelFile = new javax.swing.JLabel();
        file1 = new javax.swing.JTextField();
        btnBrowse1 = new javax.swing.JButton();
        labelPicture = new javax.swing.JLabel();
        file2 = new javax.swing.JTextField();
        btnBrowse2 = new javax.swing.JButton();
        labelKey = new javax.swing.JLabel();
        key = new javax.swing.JTextField();
        labelOptions = new javax.swing.JLabel();
        vigenere = new javax.swing.JCheckBox();
        opt1 = new javax.swing.JRadioButton();
        opt2 = new javax.swing.JRadioButton();
        imgBefore = new javax.swing.JPanel();
        imgAfter = new javax.swing.JPanel();
        btnGo = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        valPSNR = new javax.swing.JLabel();
        scrollpane1 = new javax.swing.JScrollPane();
        plaintext = new javax.swing.JTextArea();
        labelBefore = new javax.swing.JLabel();
        labelAfter = new javax.swing.JLabel();
        decryptPanel = new javax.swing.JPanel();
        fileD = new javax.swing.JTextField();
        labelPictureD = new javax.swing.JLabel();
        btnBrowseD = new javax.swing.JButton();
        labelKeyD = new javax.swing.JLabel();
        keyD = new javax.swing.JTextField();
        labelBeforeD = new javax.swing.JLabel();
        imgBeforeD = new javax.swing.JPanel();
        labelAfterD = new javax.swing.JLabel();
        imgAfterD = new javax.swing.JPanel();
        btnGoD = new javax.swing.JButton();
        valPSNRD = new javax.swing.JLabel();
        btnSavePict = new javax.swing.JButton();
        scrollpane2 = new javax.swing.JScrollPane();
        plaintextD = new javax.swing.JTextArea();
        btnSavePlaintext = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        javax.swing.JMenu fileMenu = new javax.swing.JMenu();
        javax.swing.JMenuItem exitMenuItem = new javax.swing.JMenuItem();
        javax.swing.JMenu helpMenu = new javax.swing.JMenu();
        javax.swing.JMenuItem aboutMenuItem = new javax.swing.JMenuItem();
        statusPanel = new javax.swing.JPanel();
        javax.swing.JSeparator statusPanelSeparator = new javax.swing.JSeparator();
        statusMessageLabel = new javax.swing.JLabel();
        statusAnimationLabel = new javax.swing.JLabel();
        progressBar = new javax.swing.JProgressBar();
        bgOptions = new javax.swing.ButtonGroup();

        mainPanel.setName("mainPanel"); // NOI18N

        tabbedPane.setName("tabbedPane"); // NOI18N

        encryptPanel.setName("encryptPanel"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(stegano.SteganoApp.class).getContext().getResourceMap(SteganoView.class);
        labelFile.setText(resourceMap.getString("labelFile.text")); // NOI18N
        labelFile.setName("labelFile"); // NOI18N

        file1.setText(resourceMap.getString("file1.text")); // NOI18N
        file1.setName("file1"); // NOI18N

        btnBrowse1.setText(resourceMap.getString("btnBrowse1.text")); // NOI18N
        btnBrowse1.setName("btnBrowse1"); // NOI18N

        labelPicture.setText(resourceMap.getString("labelPicture.text")); // NOI18N
        labelPicture.setName("labelPicture"); // NOI18N

        file2.setName("file2"); // NOI18N

        btnBrowse2.setText(resourceMap.getString("btnBrowse2.text")); // NOI18N
        btnBrowse2.setName("btnBrowse2"); // NOI18N

        labelKey.setText(resourceMap.getString("labelKey.text")); // NOI18N
        labelKey.setName("labelKey"); // NOI18N

        key.setName("key"); // NOI18N

        labelOptions.setText(resourceMap.getString("labelOptions.text")); // NOI18N
        labelOptions.setName("labelOptions"); // NOI18N

        vigenere.setText(resourceMap.getString("vigenere.text")); // NOI18N
        vigenere.setName("vigenere"); // NOI18N

        opt1.setText(resourceMap.getString("opt1.text")); // NOI18N
        opt1.setName("opt1"); // NOI18N

        opt2.setText(resourceMap.getString("opt2.text")); // NOI18N
        opt2.setName("opt2"); // NOI18N

        imgBefore.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        imgBefore.setName("imgBefore"); // NOI18N

        javax.swing.GroupLayout imgBeforeLayout = new javax.swing.GroupLayout(imgBefore);
        imgBefore.setLayout(imgBeforeLayout);
        imgBeforeLayout.setHorizontalGroup(
            imgBeforeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 408, Short.MAX_VALUE)
        );
        imgBeforeLayout.setVerticalGroup(
            imgBeforeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 348, Short.MAX_VALUE)
        );

        imgAfter.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        imgAfter.setName("imgAfter"); // NOI18N

        javax.swing.GroupLayout imgAfterLayout = new javax.swing.GroupLayout(imgAfter);
        imgAfter.setLayout(imgAfterLayout);
        imgAfterLayout.setHorizontalGroup(
            imgAfterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 408, Short.MAX_VALUE)
        );
        imgAfterLayout.setVerticalGroup(
            imgAfterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 348, Short.MAX_VALUE)
        );

        btnGo.setText(resourceMap.getString("btnGo.text")); // NOI18N
        btnGo.setName("btnGo"); // NOI18N

        btnSave.setText(resourceMap.getString("btnSave.text")); // NOI18N
        btnSave.setName("btnSave"); // NOI18N

        valPSNR.setText(resourceMap.getString("valPSNR.text")); // NOI18N
        valPSNR.setName("valPSNR"); // NOI18N

        scrollpane1.setName("scrollpane1"); // NOI18N

        plaintext.setColumns(20);
        plaintext.setFont(resourceMap.getFont("plaintext.font")); // NOI18N
        plaintext.setLineWrap(true);
        plaintext.setRows(5);
        plaintext.setWrapStyleWord(true);
        plaintext.setName("plaintext"); // NOI18N
        scrollpane1.setViewportView(plaintext);

        labelBefore.setText(resourceMap.getString("labelBefore.text")); // NOI18N
        labelBefore.setName("labelBefore"); // NOI18N

        labelAfter.setText(resourceMap.getString("labelAfter.text")); // NOI18N
        labelAfter.setName("labelAfter"); // NOI18N

        javax.swing.GroupLayout encryptPanelLayout = new javax.swing.GroupLayout(encryptPanel);
        encryptPanel.setLayout(encryptPanelLayout);
        encryptPanelLayout.setHorizontalGroup(
            encryptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(encryptPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(encryptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(encryptPanelLayout.createSequentialGroup()
                        .addComponent(labelFile)
                        .addGap(27, 27, 27)
                        .addGroup(encryptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(encryptPanelLayout.createSequentialGroup()
                                .addComponent(file1, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBrowse1))
                            .addComponent(scrollpane1, javax.swing.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE))
                        .addGap(26, 26, 26)
                        .addGroup(encryptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelOptions)
                            .addGroup(encryptPanelLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(encryptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(opt1)
                                    .addComponent(vigenere)
                                    .addComponent(opt2))))
                        .addGap(287, 287, 287))
                    .addGroup(encryptPanelLayout.createSequentialGroup()
                        .addGroup(encryptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(encryptPanelLayout.createSequentialGroup()
                                .addGroup(encryptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelPicture)
                                    .addComponent(labelKey))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(encryptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(key, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
                                    .addComponent(file2, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBrowse2)
                                .addGap(436, 436, 436))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, encryptPanelLayout.createSequentialGroup()
                                .addGroup(encryptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnGo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(imgBefore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelBefore))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                                .addGroup(encryptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, encryptPanelLayout.createSequentialGroup()
                                        .addComponent(valPSNR)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnSave))
                                    .addComponent(labelAfter)
                                    .addComponent(imgAfter, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap())))
        );
        encryptPanelLayout.setVerticalGroup(
            encryptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(encryptPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(encryptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(encryptPanelLayout.createSequentialGroup()
                        .addGroup(encryptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelFile)
                            .addComponent(file1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBrowse1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(scrollpane1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(encryptPanelLayout.createSequentialGroup()
                        .addComponent(labelOptions)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(vigenere)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(opt1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(opt2)))
                .addGap(6, 6, 6)
                .addGroup(encryptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelPicture)
                    .addGroup(encryptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(file2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnBrowse2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(encryptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelKey)
                    .addComponent(key, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(encryptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelBefore)
                    .addComponent(labelAfter))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(encryptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imgBefore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(imgAfter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(encryptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSave)
                    .addGroup(encryptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(valPSNR)
                        .addComponent(btnGo)))
                .addGap(21, 21, 21))
        );

        tabbedPane.addTab(resourceMap.getString("encryptPanel.TabConstraints.tabTitle"), encryptPanel); // NOI18N

        decryptPanel.setName("decryptPanel"); // NOI18N

        fileD.setName("fileD"); // NOI18N

        labelPictureD.setText(resourceMap.getString("labelPictureD.text")); // NOI18N
        labelPictureD.setName("labelPictureD"); // NOI18N

        btnBrowseD.setText(resourceMap.getString("btnBrowseD.text")); // NOI18N
        btnBrowseD.setName("btnBrowseD"); // NOI18N

        labelKeyD.setText(resourceMap.getString("labelKeyD.text")); // NOI18N
        labelKeyD.setName("labelKeyD"); // NOI18N

        keyD.setName("keyD"); // NOI18N

        labelBeforeD.setText(resourceMap.getString("labelBeforeD.text")); // NOI18N
        labelBeforeD.setName("labelBeforeD"); // NOI18N

        imgBeforeD.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        imgBeforeD.setName("imgBeforeD"); // NOI18N

        javax.swing.GroupLayout imgBeforeDLayout = new javax.swing.GroupLayout(imgBeforeD);
        imgBeforeD.setLayout(imgBeforeDLayout);
        imgBeforeDLayout.setHorizontalGroup(
            imgBeforeDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 408, Short.MAX_VALUE)
        );
        imgBeforeDLayout.setVerticalGroup(
            imgBeforeDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 348, Short.MAX_VALUE)
        );

        labelAfterD.setText(resourceMap.getString("labelAfterD.text")); // NOI18N
        labelAfterD.setName("labelAfterD"); // NOI18N

        imgAfterD.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        imgAfterD.setName("imgAfterD"); // NOI18N

        javax.swing.GroupLayout imgAfterDLayout = new javax.swing.GroupLayout(imgAfterD);
        imgAfterD.setLayout(imgAfterDLayout);
        imgAfterDLayout.setHorizontalGroup(
            imgAfterDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 408, Short.MAX_VALUE)
        );
        imgAfterDLayout.setVerticalGroup(
            imgAfterDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 348, Short.MAX_VALUE)
        );

        btnGoD.setText(resourceMap.getString("btnGoD.text")); // NOI18N
        btnGoD.setName("btnGoD"); // NOI18N

        valPSNRD.setText(resourceMap.getString("valPSNRD.text")); // NOI18N
        valPSNRD.setName("valPSNRD"); // NOI18N

        btnSavePict.setText(resourceMap.getString("btnSavePict.text")); // NOI18N
        btnSavePict.setName("btnSavePict"); // NOI18N

        scrollpane2.setName("scrollpane2"); // NOI18N

        plaintextD.setColumns(20);
        plaintextD.setFont(resourceMap.getFont("plaintextD.font")); // NOI18N
        plaintextD.setLineWrap(true);
        plaintextD.setRows(5);
        plaintextD.setText(resourceMap.getString("plaintextD.text")); // NOI18N
        plaintextD.setWrapStyleWord(true);
        plaintextD.setName("plaintextD"); // NOI18N
        scrollpane2.setViewportView(plaintextD);

        btnSavePlaintext.setText(resourceMap.getString("btnSavePlaintext.text")); // NOI18N
        btnSavePlaintext.setName("btnSavePlaintext"); // NOI18N

        javax.swing.GroupLayout decryptPanelLayout = new javax.swing.GroupLayout(decryptPanel);
        decryptPanel.setLayout(decryptPanelLayout);
        decryptPanelLayout.setHorizontalGroup(
            decryptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(decryptPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(decryptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(decryptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(decryptPanelLayout.createSequentialGroup()
                            .addGroup(decryptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(labelPictureD)
                                .addComponent(labelKeyD))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(decryptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(decryptPanelLayout.createSequentialGroup()
                                    .addComponent(fileD, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnBrowseD)
                                    .addGap(446, 446, 446))
                                .addGroup(decryptPanelLayout.createSequentialGroup()
                                    .addComponent(keyD, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
                                    .addGap(519, 519, 519))))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, decryptPanelLayout.createSequentialGroup()
                            .addGroup(decryptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnGoD, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(imgBeforeD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(labelBeforeD))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                            .addGroup(decryptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, decryptPanelLayout.createSequentialGroup()
                                    .addComponent(valPSNRD)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnSavePict))
                                .addComponent(labelAfterD)
                                .addComponent(imgAfterD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(scrollpane2))
                            .addContainerGap()))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, decryptPanelLayout.createSequentialGroup()
                        .addComponent(btnSavePlaintext)
                        .addContainerGap())))
        );
        decryptPanelLayout.setVerticalGroup(
            decryptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(decryptPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(decryptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelPictureD)
                    .addGroup(decryptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(fileD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnBrowseD)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(decryptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelKeyD)
                    .addComponent(keyD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(decryptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelBeforeD)
                    .addComponent(labelAfterD))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(decryptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imgBeforeD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(imgAfterD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(decryptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSavePict)
                    .addGroup(decryptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(valPSNRD)
                        .addComponent(btnGoD)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollpane2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSavePlaintext)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabbedPane.addTab(resourceMap.getString("decryptPanel.TabConstraints.tabTitle"), decryptPanel); // NOI18N

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 860, Short.MAX_VALUE)
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 655, Short.MAX_VALUE)
        );

        menuBar.setName("menuBar"); // NOI18N

        fileMenu.setText(resourceMap.getString("fileMenu.text")); // NOI18N
        fileMenu.setName("fileMenu"); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(stegano.SteganoApp.class).getContext().getActionMap(SteganoView.class, this);
        exitMenuItem.setAction(actionMap.get("quit")); // NOI18N
        exitMenuItem.setName("exitMenuItem"); // NOI18N
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        helpMenu.setText(resourceMap.getString("helpMenu.text")); // NOI18N
        helpMenu.setName("helpMenu"); // NOI18N

        aboutMenuItem.setAction(actionMap.get("showAboutBox")); // NOI18N
        aboutMenuItem.setName("aboutMenuItem"); // NOI18N
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        statusPanel.setName("statusPanel"); // NOI18N

        statusPanelSeparator.setName("statusPanelSeparator"); // NOI18N

        statusMessageLabel.setName("statusMessageLabel"); // NOI18N

        statusAnimationLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        statusAnimationLabel.setName("statusAnimationLabel"); // NOI18N

        progressBar.setName("progressBar"); // NOI18N

        javax.swing.GroupLayout statusPanelLayout = new javax.swing.GroupLayout(statusPanel);
        statusPanel.setLayout(statusPanelLayout);
        statusPanelLayout.setHorizontalGroup(
            statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(statusPanelSeparator, javax.swing.GroupLayout.DEFAULT_SIZE, 860, Short.MAX_VALUE)
            .addGroup(statusPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(statusMessageLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 690, Short.MAX_VALUE)
                .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(statusAnimationLabel)
                .addContainerGap())
        );
        statusPanelLayout.setVerticalGroup(
            statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statusPanelLayout.createSequentialGroup()
                .addComponent(statusPanelSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(statusMessageLabel)
                    .addComponent(statusAnimationLabel)
                    .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3))
        );

        setComponent(mainPanel);
        setMenuBar(menuBar);
        setStatusBar(statusPanel);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgOptions;
    private javax.swing.JButton btnBrowse1;
    private javax.swing.JButton btnBrowse2;
    private javax.swing.JButton btnBrowseD;
    private javax.swing.JButton btnGo;
    private javax.swing.JButton btnGoD;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSavePict;
    private javax.swing.JButton btnSavePlaintext;
    private javax.swing.JPanel decryptPanel;
    private javax.swing.JPanel encryptPanel;
    private javax.swing.JTextField file1;
    private javax.swing.JTextField file2;
    private javax.swing.JTextField fileD;
    private javax.swing.JPanel imgAfter;
    private javax.swing.JPanel imgAfterD;
    private javax.swing.JPanel imgBefore;
    private javax.swing.JPanel imgBeforeD;
    private javax.swing.JTextField key;
    private javax.swing.JTextField keyD;
    private javax.swing.JLabel labelAfter;
    private javax.swing.JLabel labelAfterD;
    private javax.swing.JLabel labelBefore;
    private javax.swing.JLabel labelBeforeD;
    private javax.swing.JLabel labelFile;
    private javax.swing.JLabel labelKey;
    private javax.swing.JLabel labelKeyD;
    private javax.swing.JLabel labelOptions;
    private javax.swing.JLabel labelPicture;
    private javax.swing.JLabel labelPictureD;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JRadioButton opt1;
    private javax.swing.JRadioButton opt2;
    private javax.swing.JTextArea plaintext;
    private javax.swing.JTextArea plaintextD;
    private javax.swing.JProgressBar progressBar;
    private javax.swing.JScrollPane scrollpane1;
    private javax.swing.JScrollPane scrollpane2;
    private javax.swing.JLabel statusAnimationLabel;
    private javax.swing.JLabel statusMessageLabel;
    private javax.swing.JPanel statusPanel;
    private javax.swing.JTabbedPane tabbedPane;
    private javax.swing.JLabel valPSNR;
    private javax.swing.JLabel valPSNRD;
    private javax.swing.JCheckBox vigenere;
    // End of variables declaration//GEN-END:variables

    private final Timer messageTimer;
    private final Timer busyIconTimer;
    private final Icon idleIcon;
    private final Icon[] busyIcons = new Icon[15];
    private int busyIconIndex = 0;

    private JDialog aboutBox;
}
